import sharp from 'sharp';
import { expect, test } from '@playwright/test';
import { createServer, type Server } from 'node:http';
import { mkdir } from 'node:fs/promises';
import { handleRequest } from '../../plugins/narracut/src/server';
import { installAppToolBridge, validResult } from '../helpers/workbench-fixture';
import { CandidateDelivery } from '../../src/shared/candidate-delivery';
let host: Server, origin: string;
test.beforeAll(async () => {
  const resource = await handleRequest({ jsonrpc:'2.0',id:1,method:'resources/read',params:{uri:'ui://narracut/workbench-v1.html'} }) as any;
  host = createServer((_req,res) => res.end(resource.contents[0].text));
  await new Promise<void>(resolve => host.listen(0,'127.0.0.1',resolve)); origin = `http://127.0.0.1:${(host.address() as any).port}`;
});
test.afterAll(async () => { host?.closeAllConnections(); await new Promise<void>(resolve => host ? host.close(() => resolve()) : resolve()); });
test('Preview 先于交付摘要，警告及建议展开，采集与检查分离；桌面与窄屏保持完整证据', async ({page}) => {
  const scenes = validResult().scenes.slice(0,2).map((scene,i) => ({id:scene.id,time:{startFrame:i*3,durationInFrames:3}}));
  const identity = {project:'p',program:'program',baseline:'baseline',brief:'brief',input:'input',media:'media',environment:'environment'};
  const set = new CandidateDelivery('delivery', {instanceId:'preview',bundle:'bundle',identity}, {durationInFrames:6,scenes});
  set.describe({goal:'让开场更清晰',summary:'调整标题位置，保留原有旁白与 Scene 顺序。',warnings:['开场停留时间较短，请结合成片判断节奏。'],suggestions:[{sceneId:scenes[1].id,observation:'第二段信息较密集',action:'精简旁白',content:'保留重点事实',reason:'为画面留出阅读时间'}]});
  for (const point of set.view().frames) set.capture(point.frame,`digest-${point.frame}`);
  const imageData = await Promise.all(Array.from({length:6},(_,frame)=>sharp(Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="${frame<3?'#19322b':'#24394f'}"/><rect x="${40+frame*60}" y="85" width="100" height="100" rx="8" fill="#e1bd79"/><text x="40" y="270" fill="#f1f3eb" font-size="36">Scene ${frame<3?1:2} / Frame ${frame}</text><text x="40" y="320" fill="#aab3b0" font-size="22">Narracut test fixture</text></svg>`)).png().toBuffer().then(bytes=>bytes.toString('base64'))));
  let stale = false, images = 0;
  await page.goto(origin);
  await installAppToolBridge(page,(name,args) => {
    if(!['project_delivery','project_delivery_display'].includes(name)) return {structuredContent:{}};
    if(name==='project_delivery_display')set.displayWarnings(args.reportRevision);
    if(args.action==='image'){images++;return {structuredContent:{digest:`digest-${args.frame}`},content:[{type:'image',mimeType:'image/png',data:imageData[args.frame]}]};}
    return {structuredContent:{delivery:{...set.view(),stale},collecting:false,status:stale?'stale':'incomplete',checks:{batches:[{id:'batch',identity,status:'complete',stale:false,diagnostics:[],visualWarnings:[],truncated:0,warningsTruncated:0,stages:[{id:'manifest',status:'passed'},{id:'build',status:'passed'}]}],gates:[]}}};
  });
  await page.evaluate(result=>window.postMessage({jsonrpc:'2.0',method:'ui/notifications/tool-result',params:{structuredContent:result}},'*'),{...validResult(),candidate:{status:'saved',candidate:{identity:'program'},baseline:'baseline'}});
  await page.getByRole('tab',{name:'Agent 工作区'}).click();
  await expect(page.locator('[data-delivery-summary]')).toContainText('让开场更清晰');
  expect(await page.locator('[data-program-delivery]').evaluate(el=>!!(el.compareDocumentPosition(document.querySelector('[data-program-preview]')!) & Node.DOCUMENT_POSITION_PRECEDING))).toBe(true);
  await expect(page.locator('[data-delivery-progress]')).toContainText('已采集 6 / 6');
  await expect(page.locator('[data-delivery-progress]')).toContainText('已检查 0 / 6');
  await expect(page.getByText('开场停留时间较短，请结合成片判断节奏。',{exact:true})).toBeVisible();
  await expect(page.getByText('第二段信息较密集',{exact:true})).toBeVisible();
  expect(images).toBe(0);
  await page.getByText('展开代表帧证据',{exact:true}).click();
  await expect(page.locator('[data-delivery-frames] img').first()).toBeVisible();
  await expect(page.locator('[data-boundary]').first()).toContainText('帧 2');
  await expect(page.locator('[data-boundary]').first()).toContainText('帧 3');
  const selected=await page.locator('.scene-select[aria-pressed="true"]').getAttribute('aria-label');
  const small = await page.locator('[data-enlarge]').first().boundingBox();
  await page.locator('[data-enlarge]').first().click();
  const large = await page.locator('[data-enlarge]').first().boundingBox();
  expect(large!.width).toBeGreaterThan(small!.width * 1.5);
  expect(await page.locator('.scene-select[aria-pressed="true"]').getAttribute('aria-label')).toBe(selected);
  await mkdir('.impeccable/review',{recursive:true});
  await page.locator('[data-delivery-frames] figure').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:'.impeccable/review/delivery-desktop-enlarged.png',fullPage:true});
  await page.locator('#workspace-agent').evaluate(el=>el.scrollTop=0);
  await page.screenshot({path:'.impeccable/review/delivery-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'.impeccable/review/delivery-mobile.png',fullPage:true});
  await page.locator('[data-boundary]').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:'.impeccable/review/delivery-mobile-frames.png',fullPage:true});
  const before = await page.locator('[data-boundary] [data-enlarge]').first().boundingBox();
  await page.locator('[data-boundary] [data-enlarge]').first().click();
  const after = await page.locator('[data-boundary] [data-enlarge]').first().boundingBox();
  expect(after!.width).toBeGreaterThan(before!.width * 1.5);
  await expect(page.locator('[data-boundary] [data-enlarge]').first()).toHaveAttribute('aria-expanded','true');
  await page.locator('[data-boundary]').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:'.impeccable/review/delivery-mobile-enlarged.png',fullPage:true});
  await page.evaluate(result=>window.postMessage({jsonrpc:'2.0',method:'ui/notifications/tool-result',params:{structuredContent:result}},'*'), { ...validResult(1), projectRevision: 'sha256:' + '2'.repeat(64) });
  await expect(page.locator('[data-go-scene="0"]')).toBeDisabled({ timeout: 10000 });
  await expect(page.locator('[data-delivery-suggestions]')).toContainText('目标 Scene 已删除');
  stale=true;await expect(page.locator('[data-delivery-state]')).toContainText('已过期',{timeout:10000});
});
test('超过四个 Scene 的分页保持键盘上下文与完整计划',async({page})=>{
  const scenes=validResult(9).scenes.map((scene,i)=>({id:scene.id,time:{startFrame:i*3,durationInFrames:3}}));
  const identity={project:'p',program:'program',baseline:'baseline',brief:'brief',input:'input',media:'media',environment:'environment'};
  const set=new CandidateDelivery('many',{instanceId:'preview',bundle:'bundle',identity},{durationInFrames:27,scenes});
  await page.goto(origin);
  await installAppToolBridge(page,(name)=>name==='project_delivery'?{structuredContent:{delivery:set.view(),collecting:false,status:'incomplete',checks:{batches:[],gates:[]},output:{fps:30}}}:{structuredContent:{}});
  await page.evaluate(result=>window.postMessage({jsonrpc:'2.0',method:'ui/notifications/tool-result',params:{structuredContent:result}},'*'),{...validResult(9),candidate:{status:'saved',candidate:{identity:'program'},baseline:'baseline'}});
  await page.getByRole('tab',{name:'Agent 工作区'}).click();
  await expect(page.locator('[data-delivery-progress]')).toContainText('基础覆盖 27 帧');
  await page.getByText('展开代表帧证据',{exact:true}).click();
  await page.locator('[data-page="1"]').focus();await page.keyboard.press('Enter');
  await expect(page.locator('[data-page-heading]').first()).toBeFocused();
  await expect(page.locator('[data-page-heading]').first()).toContainText('Scene 5');
  await page.locator('[data-page="1"]').click();
  await expect(page.locator('[data-page-heading]').first()).toContainText('Scene 9');
  await expect(page.locator('[data-page="1"]')).toBeDisabled();
  await page.locator('[data-page="-1"]').click();
  await expect(page.locator('[data-page-heading]').first()).toBeFocused();
  await expect(page.locator('[data-page-heading]').first()).toContainText('Scene 5');
  await page.getByText('完整覆盖计划与身份',{exact:true}).click();
  await expect(page.locator('[data-full-plan] li')).toHaveCount(27);
});
