import { expect, test } from '@playwright/test';
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { startWorkbenchPanel } from '../../plugins/narracut/src/workbench-panel';

test('页面编排保存重开保持 Scene 身份、顺序及 Asset，历史只留在当前页面', async ({ page }) => {
  const root = await mkdtemp(join(tmpdir(), 'scene-arrangement-'));
  const panel = await startWorkbenchPanel({ threadId: 'scene-arrangement-owner' });
  const directory = join(root, '编排验证');
  const call = async (name: string, args = {}) => {
    const response = await page.request.post(`${panel.url}rpc`, { headers: { Origin: new URL(panel.url).origin }, data: { id: 1, method: 'tools/call', params: { name, arguments: args } } });
    const result = (await response.json()).result;
    expect(result.isError, JSON.stringify(result)).not.toBe(true);
    return result.structuredContent;
  };
  const disk = async () => JSON.parse(await readFile(join(directory, 'project.json'), 'utf8'));
  try {
    const created = await call('create_project', { projectDirectory: directory });
    const sourcePath = join(root, '保留的 Asset.txt');
    await writeFile(sourcePath, '删除 Scene 不得删除此 Asset');
    await page.goto(panel.url);
    const app = page.frameLocator('iframe');
    await app.getByRole('button', { name: '新增第一个 Scene' }).click();
    await app.getByRole('textbox', { name: 'Scene 01 Narration' }).fill('第一句');
    await app.getByRole('textbox', { name: 'Scene 01 Narration' }).blur();
    await expect.poll(async () => (await disk()).scenes[0]?.narration.text).toBe('第一句');
    const originalId = (await disk()).scenes[0].id;
    const latest = await call('get_workbench');
    await call('import_project_asset', { projectDirectory: directory, projectId: created.project.projectId, baselineRevision: latest.projectRevision, sourcePath, targetSceneId: originalId });
    await page.reload();
    const original = app.getByRole('group', { name: 'Scene 01 行', exact: true });
    await original.click();
    await app.getByRole('button', { name: '新增 Scene', exact: true }).click();
    const editor = app.getByRole('textbox', { name: 'Scene 02 Narration' });
    await expect(editor).toBeFocused();
    await editor.fill('第二句'); await editor.blur();
    await expect.poll(async () => (await disk()).scenes[1]?.narration.text).toBe('第二句');
    const secondId = (await disk()).scenes[1].id;
    await original.click({ button: 'right' });
    await app.getByRole('menuitem', { name: '复制', exact: true }).click();
    await expect.poll(async () => (await disk()).scenes.length).toBe(3);
    const copy = (await disk()).scenes[1];
    expect(copy.id).not.toBe(originalId);
    expect(copy.narration.text).toBe('第一句');
    expect(copy.assetIds).toEqual((await disk()).scenes[0].assetIds);
    expect(copy.speech).toBeUndefined();
    const copied = app.getByRole('group', { name: 'Scene 02 行', exact: true });
    await expect(copied).toBeFocused();
    await expect(app.getByRole('textbox')).toHaveCount(0);
    await copied.press('Shift+F10');
    await app.getByRole('spinbutton', { name: '移动到位置' }).fill('3');
    await app.getByRole('menuitem', { name: '移动', exact: true }).click();
    await expect.poll(async () => (await disk()).scenes.map((s: { id: string }) => s.id)).toEqual([originalId, secondId, copy.id]);
    const moved = app.getByRole('group', { name: 'Scene 03 行', exact: true });
    await expect(moved).toBeFocused();
    await moved.press('Shift+F10');
    await app.getByRole('menuitem', { name: '删除', exact: true }).click();
    await expect.poll(async () => (await disk()).scenes.length).toBe(2);
    await expect(app.getByRole('group', { name: 'Scene 02 行', exact: true })).toBeFocused();
    await app.getByRole('button', { name: '撤销删除', exact: true }).click();
    await expect.poll(async () => (await disk()).scenes[2]?.id).toBe(copy.id);
    const saved = await disk();
    expect(await readFile(join(directory, saved.assets[0].path), 'utf8')).toBe('删除 Scene 不得删除此 Asset');
    await page.reload();
    await expect(app.getByRole('button', { name: '没有可撤销的记录' })).toBeDisabled();
    await expect(app.getByRole('group', { name: 'Scene 03 行', exact: true })).toContainText('第一句');
    expect(await disk()).toEqual(saved);
  } finally { await page.close(); await panel.close(); await rm(root, { recursive: true, force: true }); }
});
