import { ProjectAcceptance } from '../src/server/project-acceptance';
import { expect, test, vi } from 'vitest';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { parse } from 'yaml';
import { fixture } from './helpers/program-fixture';
import { createProjectVNext, openProjectVNext } from '../src/server/project-lifecycle';
import { ProjectPreview } from '../src/server/project-preview';
import { ProjectChecks } from '../src/server/project-checks';
import { ProjectDelivery } from '../src/server/project-delivery';
test('完整服务协议从准确实例采集到单独检查、警告展示与交付；变更立即关闭交付门禁', async () => {
  const root=await mkdtemp(join(tmpdir(),'delivery-')), directory=join(root,'project');
  await createProjectVNext(directory); const request=await fixture();
  const revision=JSON.parse(await readFile(join(directory,'.narracut/current.json'),'utf8')).revisionId;
  for(const [file,bytes] of request.program)await writeFile(join(directory,'.narracut/revisions',revision,'render-program',file),bytes);
  const lock=parse(request.program.get('pnpm-lock.yaml')!.toString()); const urls=new Map<string,Buffer>();
  for(const [id,value] of Object.entries(lock.packages) as [string,any][]){const split=id.lastIndexOf('@'),name=id.slice(0,split),version=id.slice(split+1);urls.set(`https://registry.npmjs.org/${name}/-/${name}-${version}.tgz`,request.offline.get(Buffer.from(value.resolution.integrity.slice(7),'base64').toString('hex'))!);}
  vi.stubGlobal('fetch',vi.fn(async(url:string)=>new Response(new Uint8Array(urls.get(url)!))));
  const opened=await openProjectVNext(directory), preview=new ProjectPreview(), checks=new ProjectChecks(preview), delivery=new ProjectDelivery(preview,checks);
  try {
    await writeFile(join(directory,'project.json'),JSON.stringify({assets:[],scenes:[{id:'30000000-0000-4000-8000-000000000001',narration:{text:'测试旁白'},assetIds:[]}]}));
    const candidate=await opened.candidate({action:'create'});
    await opened.candidate({action:'dependencies',baseline:candidate.baseline,dependencies:{},packages:[]});
    const descriptor=await preview.build(opened,'candidate','http://127.0.0.1:45678');
    await checks.start(opened);
    await delivery.operate(opened,{action:'prepare',instanceId:descriptor.instanceId});
    let state=await delivery.status(opened);
    for(let attempt=0;attempt<100 && (state.collecting || state.checks.batches.at(-1)?.status==='running');attempt++){await new Promise(resolve=>setTimeout(resolve,100));state=await delivery.status(opened);}
    expect(state.delivery?.captured).toBe(3);expect(state.delivery?.checked).toBe(0);
    expect(state.checks.gates.find(gate=>gate.operation==='delivery')?.status).toBe('blocked');
    const id=state.delivery!.id;
    const frame=state.delivery!.frames[0];
    await expect(delivery.operate(opened,{action:'review',deliveryId:id,reviews:[{frame:frame.frame,digest:frame.digest,observation:'尚未读取图像'}]})).rejects.toThrow('读取');
    for(const frame of state.delivery!.frames){const image=await delivery.operate(opened,{action:'image',deliveryId:id,frame:frame.frame});expect(image).toMatchObject({binding:{instanceId:descriptor.instanceId},digest:frame.digest});}
    await delivery.operate(opened,{action:'review',deliveryId:id,reviews:state.delivery!.frames.map(frame=>({frame:frame.frame,digest:frame.digest,observation:'文字可见，画面未遮挡'}))});
    await delivery.operate(opened,{action:'describe',deliveryId:id,report:{goal:'验证完整候选',summary:'调整成片表现',warnings:['节奏需由用户判断'],suggestions:[]}});
    state=await delivery.status(opened);
    await delivery.operate(opened,{action:'displayed',deliveryId:id,reportRevision:state.delivery!.reportRevision,batchId:state.checks.batches.at(-1)!.id,warningsKey:state.warningsKey});
    state=await delivery.status(opened);expect(state.status).toBe('ready');
    expect(state.checks.gates.map(gate=>gate.status)).toEqual(['available','available','blocked','disabled']);
    await checks.start(opened);
    state=await delivery.status(opened);
    for(let attempt=0;attempt<100 && state.checks.batches.at(-1)?.status==='running';attempt++){await new Promise(resolve=>setTimeout(resolve,100));state=await delivery.status(opened);}
    expect(state.status).toBe('incomplete');
    expect(state.checks.gates.find(gate=>gate.operation==='delivery')?.status).toBe('blocked');
    await delivery.operate(opened,{action:'displayed',deliveryId:id,reportRevision:state.delivery!.reportRevision,batchId:state.checks.batches.at(-1)!.id,warningsKey:state.warningsKey});
    expect((await delivery.status(opened)).status).toBe('ready');
    const nonemptyAcceptance = new ProjectAcceptance(delivery, preview);
    const nonemptyReview = await nonemptyAcceptance.operate(opened, { action: 'review' });
    const nonemptyResult = await nonemptyAcceptance.operate(opened, { action: 'accept', ...nonemptyReview.confirmation, confirmed: true });
    expect(nonemptyResult.revision.acceptance.frames).toHaveLength(3);
    expect(nonemptyResult.revision.acceptance.frames.every((frame:any) => frame.digest.startsWith('sha256:') && !('image' in frame) && !('observation' in frame))).toBe(true);
    expect(nonemptyResult.revision.acceptance.warnings).toContain('节奏需由用户判断');
    await opened.candidate({action:'create'});
    await writeFile(join(directory,'video.md'),'新的要求');
    state=await delivery.status(opened);expect(state.delivery).toBeNull();
    await expect(delivery.operate(opened,{action:'review',deliveryId:id,reviews:[]})).rejects.toThrow();
    await writeFile(join(directory,'project.json'),JSON.stringify({assets:[],scenes:[]}));
    const empty=await preview.build(opened,'candidate','http://127.0.0.1:45678');
    await checks.start(opened);await delivery.operate(opened,{action:'prepare',instanceId:empty.instanceId});
    state=await delivery.status(opened);
    for(let attempt=0;attempt<100 && state.checks.batches.at(-1)?.status==='running';attempt++){await new Promise(resolve=>setTimeout(resolve,100));state=await delivery.status(opened);}
    expect(state.delivery?.zeroScenes).toBe(true);expect(state.delivery?.frames).toEqual([]);expect(state.collecting).toBe(false);
    expect(state.checks.batches.at(-1)?.stages.filter(stage=>['manifest','build'].includes(stage.id)).every(stage=>stage.status==='passed')).toBe(true);
    await delivery.operate(opened,{action:'describe',deliveryId:state.delivery!.id,report:{goal:'建立空项目程序',summary:'保留有效 Manifest 与构建',warnings:[],suggestions:[]}});
    state=await delivery.status(opened);
    await delivery.operate(opened,{action:'displayed',deliveryId:state.delivery!.id,reportRevision:state.delivery!.reportRevision,batchId:state.checks.batches.at(-1)!.id,warningsKey:state.warningsKey});
    expect((await delivery.status(opened)).status).toBe('ready');
    await nonemptyAcceptance.operate(opened, { action: 'result', requestId: nonemptyReview.confirmation.requestId });
    expect((await delivery.status(opened)).status).toBe('ready');
    const acceptance = new ProjectAcceptance(delivery, preview);
    const firstReview = await acceptance.operate(opened, { action: 'review' });
    await delivery.operate(opened,{action:'describe',deliveryId:state.delivery!.id,report:{goal:'建立空项目程序',summary:'更新确认摘要',warnings:['需要重新审阅'],suggestions:[]}});
    await expect(acceptance.operate(opened, { action: 'accept', ...firstReview.confirmation, confirmed: true })).rejects.toThrow();
    expect((await opened.candidate({action:'read'})).status).toBe('saved');
    state=await delivery.status(opened);
    await delivery.operate(opened,{action:'displayed',deliveryId:state.delivery!.id,reportRevision:state.delivery!.reportRevision,batchId:state.checks.batches.at(-1)!.id,warningsKey:state.warningsKey});
    const reviewed = await acceptance.operate(opened, { action: 'review' });
    const result = await acceptance.operate(opened, { action: 'accept', ...reviewed.confirmation, confirmed: true });
    expect(result.status).toBe('accepted');
    expect(result.revision.programFingerprint).toBe(nonemptyResult.revision.programFingerprint);
    expect(result.revision.revisionId).not.toBe(nonemptyResult.revision.revisionId);
    expect(result.revision.inputFingerprint).not.toBe(nonemptyResult.revision.inputFingerprint);
    expect(result.revision.acceptance.zeroScenes).toBe(true);
    expect(result.revision.acceptance.bundle).toBe(empty.identity.bundle);
    expect(result.revision.acceptance.warnings).toContain('需要重新审阅');
    expect(result.revision.acceptance.frames).toEqual([]);
    expect((await opened.candidate({action:'read'})).status).toBe('absent');
    expect((await acceptance.operate(opened, { action: 'result', requestId: reviewed.confirmation.requestId })).revision.revisionId).toBe(result.revision.revisionId);
    expect((await preview.status(opened, empty.instanceId)).stale).toBe(false);
    const historical = await acceptance.operate(opened, {action:'history'});
    expect(historical.revisions[0].acceptance.gates[0].status).toBe('available');
    await writeFile(join(directory,'.narracut/revisions',result.revision.revisionId,'render-program/resources/damaged.txt'),'已提交后的外部损坏');
    const reconciled = await acceptance.operate(opened, { action: 'result', requestId: reviewed.confirmation.requestId });
    expect(reconciled).toMatchObject({ status: 'accepted', revision: { revisionId: result.revision.revisionId, valid: false } });
    await rm(join(directory,'.narracut/revisions',result.revision.revisionId,'render-program/resources/damaged.txt'));
    await opened.release();
    const reopened = await openProjectVNext(directory);
    await reopened.release();
  }finally{delivery.clear();checks.clear();await preview.close();await opened.release();vi.unstubAllGlobals();await rm(root,{recursive:true,force:true});}
},120000);
